package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/InitialNameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/openjdk/jdk8u/jdk8u/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Saturday, July 25, 2020 1:24:05 AM EDT
*/


/** Interface used to support binding references in the bootstrap name
    * service.
    */
public interface InitialNameService extends InitialNameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InitialNameService
