package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/openjdk/jdk8u/jdk8u/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Saturday, July 25, 2020 1:24:05 AM EDT
*/


/** Server callback API, passed to Activator in active method.
    */
public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
